#
# Configuration file for the Samba suite for Debian GNU/Linux.
#

#======================= Global Settings =======================

[global]

# Logging
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d

# Server role
   server role = standalone server

#======================= Share Definitions =======================

[media]
   path = /data/downloads/media
   comment = Media Library
   browseable = yes
   read only = no
   guest ok = no
   valid users = 
   create mask = 0644
   directory mask = 0755
