---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

# - Examples:
#   - Example:
#     - abbr: EX
#       icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/example.png
#       href: https://example.com
